name = "infinity-hackathon-2026"
pages_build_output_dir = "dist"
compatibility_date = "2026-09-24"
compatibility_flags = [ "nodejs_compat" ]

[[r2_buckets]]
bucket_name = "infinity-hackathon-bucket"
binding = "BUCKET"

[vars]
APP_URL = "https://infinity.akao.in"
CLOUDFLARE_R2_PUBLIC_DOMAIN = "https://pub-aa1b426e7ec64c31a70bdd49676fdec1.r2.dev"
RESEND_API_KEY = "re_5r2BeM59_AnyXKqPxWm4A8ej6C9cJqXEX"
EMAIL_FROM = "Infinity Hackathon 2026 <hackathon@infinity.akao.in>"

[env.production]
compatibility_date = "2026-09-24"
compatibility_flags = [ "nodejs_compat" ]

[[env.production.r2_buckets]]
bucket_name = "infinity-hackathon-bucket"
binding = "BUCKET"

[env.production.vars]
APP_URL = "https://infinity.akao.in"
CLOUDFLARE_R2_PUBLIC_DOMAIN = "https://pub-aa1b426e7ec64c31a70bdd49676fdec1.r2.dev"
RESEND_API_KEY = "re_5r2BeM59_AnyXKqPxWm4A8ej6C9cJqXEX"
EMAIL_FROM = "Infinity Hackathon 2026 <hackathon@infinity.akao.in>"


