export const STONES = [
  {
    id: 'mind',
    index: '01',
    name: 'MIND STONE',
    roman: 'I',
    colorHex: '#ffd000',
    colorThree: 0xffd000,
    coreColor: 0xfff08a,
    darkColor: 0x665500,
    domainKey: 'transportation',
    domain: 'TRANSPORTATION & LOGISTICS',
    domainTagline: 'Mobility • Supply Chain • Routing',
    marvelTheme: 'Vision Neural Gold',
    entity: 'The Scepter / Vision\'s Core',
    origin: 'Chitauri Scepter / Neural Matrix',
    vessel: 'The Scepter / Vision',
    frequency: '528.00 THz',
    refractiveIndex: '2.54',
    powerLevel: '98.5%',
    particleCount: 180,
    techStack: ['Python', 'FastAPI', 'Mapbox / GIS', 'Kafka', 'React', 'OR-Tools'],
    quote: 'It contains an intellect of supreme cosmic density.',
    description: 'Pioneer intelligent traffic management, emergency route optimization, real-time public transit tracking, and dynamic supply chain logistics to eliminate urban congestion.',
    focusAreas: [
      { title: 'Smart Traffic Management', desc: 'Develop a software solution to analyze traffic patterns and reduce congestion through intelligent routing.' },
      { title: 'Emergency Vehicle Route Optimization', desc: 'Build a system that identifies the fastest route for ambulances, fire services, or other emergency vehicles.' },
      { title: 'Public Transport Tracking', desc: 'Create a real-time platform for tracking buses or other public transportation and estimating arrival times.' },
      { title: 'Smart Logistics & Delivery Optimization', desc: 'Develop a solution to optimize delivery routes, schedules, vehicle utilization, and operational costs.' },
      { title: 'Supply Chain Visibility', desc: 'Build a platform that improves tracking and transparency of goods across the supply chain.' },
      { title: 'Smart Parking Management', desc: 'Create a system that helps users discover, reserve, and efficiently manage available parking spaces.' }
    ],
    stats: [
      { label: 'FLEET TELEMETRY', value: 'Sub-Second' },
      { label: 'ROUTE MATRIX', value: 'Dynamic Mesh' },
      { label: 'HARMONIC', value: '528.00 THz' },
      { label: 'SLOTS OPEN', value: '12 Squads' }
    ]
  },
  {
    id: 'space',
    index: '02',
    name: 'SPACE STONE',
    roman: 'II',
    colorHex: '#00d2ff',
    colorThree: 0x00d2ff,
    coreColor: 0x80ecff,
    darkColor: 0x004066,
    domainKey: 'cybersecurity',
    domain: 'CYBERSECURITY & DIGITAL TRUST',
    domainTagline: 'Cybersecurity • Privacy • Cryptography',
    marvelTheme: 'Tesseract Cyan',
    entity: 'Tesseract (Cosmic Cube)',
    origin: 'Pre-Universe Singularity / Asgardian Vault',
    vessel: 'The Tesseract',
    frequency: '432.18 THz',
    refractiveIndex: '2.42',
    powerLevel: '99.2%',
    particleCount: 160,
    techStack: ['Rust', 'Go', 'Python', 'eBPF', 'Cryptography', 'SIEM / ELK'],
    quote: 'The Tesseract has awakened. It is on a little world, a human world.',
    description: 'Engineer resilient digital trust architectures, intelligent phishing and fraud detection, secure digital identity verification, and proactive cyber threat defense.',
    focusAreas: [
      { title: 'Phishing & Scam Detection', desc: 'Develop an intelligent system capable of identifying suspicious emails, messages, URLs, or websites.' },
      { title: 'Digital Fraud Detection', desc: 'Build a solution that identifies potentially fraudulent digital transactions or suspicious user behaviour.' },
      { title: 'Secure Digital Identity', desc: 'Create a secure identity-verification and authentication solution while protecting user privacy.' },
      { title: 'Deepfake & Manipulated Content Detection', desc: 'Develop a platform for identifying potentially manipulated images, videos, or digital content.' },
      { title: 'Privacy-Preserving Data Sharing', desc: 'Build a system that enables organizations or users to share information securely while protecting sensitive data.' },
      { title: 'Cyber Threat Monitoring', desc: 'Develop a dashboard that identifies, analyzes, and alerts users about suspicious security activities.' }
    ],
    stats: [
      { label: 'LATENCY PROFILE', value: 'Sub-5ms Mesh' },
      { label: 'DEFENSE MATRIX', value: 'Post-Quantum' },
      { label: 'HARMONIC', value: '432.18 THz' },
      { label: 'SLOTS OPEN', value: '10 Squads' }
    ]
  },
  {
    id: 'reality',
    index: '03',
    name: 'REALITY STONE',
    roman: 'III',
    colorHex: '#ff2a4b',
    colorThree: 0xff2a4b,
    coreColor: 0xff7588,
    darkColor: 0x660010,
    domainKey: 'infrastructure',
    domain: 'DIGITAL PUBLIC INFRASTRUCTURE',
    domainTagline: 'Digital Platforms • Services • E-Governance',
    marvelTheme: 'Aether Crimson',
    entity: 'The Aether (Fluid Crystal)',
    origin: 'Pre-Universe Singularity / Svartalfheim',
    vessel: 'The Aether Prism',
    frequency: '612.44 THz',
    refractiveIndex: '2.68',
    powerLevel: '97.8%',
    particleCount: 220,
    techStack: ['TypeScript', 'React', 'Next.js', 'Node.js', 'PostgreSQL', 'Flutter'],
    quote: 'It turns matter into dark matter, reshaping physical reality at will.',
    description: 'Construct unified digital public infrastructure, smart civic grievance platforms, transparent governance dashboards, and verified digital citizen services.',
    focusAreas: [
      { title: 'Smart Public Grievance System', desc: 'Build a platform where citizens can report civic problems and track their resolution.' },
      { title: 'Government Scheme Discovery', desc: 'Develop a system that helps citizens discover public schemes and services for which they may be eligible.' },
      { title: 'Unified Citizen Service Platform', desc: 'Create a single digital platform for accessing multiple public services.' },
      { title: 'Smart Civic Issue Reporting', desc: 'Develop a location-based platform for reporting issues such as damaged roads, waste, streetlights, or water problems.' },
      { title: 'Public Service Transparency Dashboard', desc: 'Build a platform for tracking service requests, progress, response times, and public-service performance.' },
      { title: 'Digital Document Verification', desc: 'Develop a secure system for verifying certificates, documents, or other public records.' }
    ],
    stats: [
      { label: 'SERVICE REACH', value: 'Citizen Scale' },
      { label: 'STATE CONFLICT', value: 'Sub-30ms CRDT' },
      { label: 'HARMONIC', value: '612.44 THz' },
      { label: 'SLOTS OPEN', value: '14 Squads' }
    ]
  },
  {
    id: 'power',
    index: '04',
    name: 'POWER STONE',
    roman: 'IV',
    colorHex: '#b026ff',
    colorThree: 0xb026ff,
    coreColor: 0xe085ff,
    darkColor: 0x4a0572,
    domainKey: 'cleantech',
    domain: 'CLEAN & GREEN TECHNOLOGY',
    domainTagline: 'Environment • Waste • Sustainability',
    marvelTheme: 'Thanos Void Purple',
    entity: 'The Orb / Morag Temple',
    origin: 'Pre-Universe Singularity / Celestial Eson',
    vessel: 'The Orb of Morag',
    frequency: '741.89 THz',
    refractiveIndex: '2.75',
    powerLevel: '100.0%',
    particleCount: 200,
    techStack: ['Python', 'IoT / ESP32', 'React', 'MQTT', 'TensorFlow', 'FastAPI'],
    quote: 'It contains an energy that destroys all organic matter it touches.',
    description: 'Develop sustainable clean technologies, intelligent waste and recycling systems, smart water conservation platforms, and real-time carbon footprint optimization.',
    focusAreas: [
      { title: 'Smart Waste Management', desc: 'Develop a platform for improving waste collection, segregation, recycling, or disposal.' },
      { title: 'Carbon Footprint Tracker', desc: 'Build an application that estimates environmental impact and recommends ways to reduce carbon emissions.' },
      { title: 'Energy Consumption Optimization', desc: 'Develop a software system that analyzes energy usage and provides recommendations for reducing consumption.' },
      { title: 'Water Conservation Platform', desc: 'Build a solution that monitors water usage, identifies wastage, and encourages conservation.' },
      { title: 'Smart Recycling Platform', desc: 'Create a system connecting households, institutions, recyclers, and waste-collection services.' },
      { title: 'Environmental Monitoring Dashboard', desc: 'Develop a platform that analyzes environmental data such as pollution, water quality, temperature, or waste generation.' }
    ],
    stats: [
      { label: 'BUS TELEMETRY', value: 'Microsecond' },
      { label: 'CARBON OFFSET', value: 'Real-Time' },
      { label: 'HARMONIC', value: '741.89 THz' },
      { label: 'SLOTS OPEN', value: '8 Squads' }
    ]
  },
  {
    id: 'time',
    index: '05',
    name: 'TIME STONE',
    roman: 'V',
    colorHex: '#00ff88',
    colorThree: 0x00ff88,
    coreColor: 0x8affc1,
    darkColor: 0x00552b,
    domainKey: 'education',
    domain: 'SMART EDUCATION',
    domainTagline: 'EdTech • Learning • Assessment',
    marvelTheme: 'Doctor Strange Emerald',
    entity: 'Eye of Agamotto / Kamar-Taj',
    origin: 'Pre-Universe Singularity / Sorcerer Supreme',
    vessel: 'Eye of Agamotto',
    frequency: '852.12 THz',
    refractiveIndex: '2.48',
    powerLevel: '98.9%',
    particleCount: 190,
    techStack: ['Python', 'LangChain', 'React', 'FastAPI', 'Node.js', 'PostgreSQL'],
    quote: 'Dormammu, I have come to bargain.',
    description: 'Architect personalized AI learning platforms, intelligent academic mentors, student performance analytics, and accessible assistive education tools.',
    focusAreas: [
      { title: 'Personalized Learning Platform', desc: 'Build a system that adapts learning content according to individual student performance and progress.' },
      { title: 'AI Learning Assistant', desc: 'Develop an intelligent assistant that helps students understand concepts, find resources, and resolve academic doubts.' },
      { title: 'Smart Assessment System', desc: 'Create a platform for conducting assessments and providing meaningful performance feedback.' },
      { title: 'Student Performance Analytics', desc: 'Develop a system that identifies learning gaps and students who may require additional academic support.' },
      { title: 'Skill Gap & Career Recommendation', desc: 'Build a platform that analyzes student skills and recommends learning paths or career opportunities.' },
      { title: 'Accessible Education Platform', desc: 'Develop software that makes digital learning more accessible for students with different learning or accessibility needs.' }
    ],
    stats: [
      { label: 'STUDENT REACH', value: 'Personalized' },
      { label: 'ORACLE HORIZON', value: 'Adaptive AI' },
      { label: 'HARMONIC', value: '852.12 THz' },
      { label: 'SLOTS OPEN', value: '11 Squads' }
    ]
  },
  {
    id: 'soul',
    index: '06',
    name: 'SOUL STONE',
    roman: 'VI',
    colorHex: '#ff7700',
    colorThree: 0xff7700,
    coreColor: 0xffd27f,
    darkColor: 0x994400,
    domainKey: 'healthcare',
    domain: 'MEDTECH / BIOTECH / HEALTHCARE',
    domainTagline: 'Healthcare • Medical AI • Assistive Technology',
    marvelTheme: 'Vormir Sunset Orange',
    entity: 'Vormir Altar / Soul World',
    origin: 'Pre-Universe Singularity / Red Skull Guardian',
    vessel: 'Vormir Shrine',
    frequency: '963.00 THz',
    refractiveIndex: '2.62',
    powerLevel: '99.7%',
    particleCount: 180,
    techStack: ['Python', 'Flutter', 'FastAPI', 'OpenCV', 'PyTorch', 'PostgreSQL'],
    quote: 'A soul for a soul. Great technological impact demands great purpose.',
    description: 'Advance transformative medical AI, remote patient diagnostic networks, emergency healthcare coordination, and accessible assistive health technologies.',
    focusAreas: [
      { title: 'Smart Healthcare Assistance', desc: 'Develop a platform that helps patients access appropriate healthcare information and services.' },
      { title: 'Remote Patient Monitoring', desc: 'Build a software solution for recording, visualizing, and communicating patient health information to authorized caregivers.' },
      { title: 'Emergency Healthcare Platform', desc: 'Create a system connecting patients with nearby hospitals, emergency services, blood banks, or other critical resources.' },
      { title: 'Medication Management', desc: 'Develop an application for medication schedules, reminders, adherence tracking, and caregiver notifications.' },
      { title: 'Healthcare Accessibility', desc: 'Build an assistive technology solution that improves access to healthcare for elderly people or people with disabilities.' },
      { title: 'Hospital Resource Management', desc: 'Develop software for efficiently managing appointments, beds, queues, staff, or other hospital resources.' }
    ],
    stats: [
      { label: 'COMMUNITY REACH', value: 'Global Impact' },
      { label: 'ETHICAL CORE', value: 'Privacy-Preserving' },
      { label: 'HARMONIC', value: '963.00 THz' },
      { label: 'SLOTS OPEN', value: '15 Squads' }
    ]
  }
];
